### ISSUE TITLE
Uglifier::Error: Unterminated string constant

### ISSUE THREAD

**Issue by elramirezv** [IIC2143-2018-1/project#66]
Hola!

Estamos intentando subir los nuevos cambios a la página, pero no nos dejar hacer push.

Todo va bien hasta que el bundler empieza a molestar :(
Esto es lo que muestra la terminal:
```
Your Gemfile lists the gem rails_admin (~> 1.3) more than once.
       You should probably keep only one of them.
       While it's not a problem now, it could cause errors if you change the version of one of them later.
       Warning: the running version of Bundler (1.15.2) is older than the version that created the lockfile (1.16.1). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
       Removing uglifier (4.1.11)
       Removing autoprefixer-rails (8.6.0)
       Removing ffi (1.9.24)
       Removing nokogiri (1.8.2)
       Removing aws-eventstream (1.0.0)
       Removing aws-sdk-core (3.21.2)
       Removing sprockets (3.7.1)
       Removing aws-sdk-s3 (1.13.0)
       Removing aws-partitions (1.90.0)
       The latest bundler is 1.16.2, but you are currently running 1.15.2.
       To update, run `gem install bundler`
-----> Installing node-v8.10.0-linux-x64
-----> Detecting rake tasks
-----> Preparing app for Rails asset pipeline
       Running: rake assets:precompile
       Yarn executable was not detected in the system.
       Download Yarn at https://yarnpkg.com/en/docs/install
       I, [2018-06-23T23:22:26.277054 #917]  INFO -- : Writing /tmp/build_60a79b6db8e344f05e2fd3adead63da5/public/assets/posts-f78f0f583e152fa235ca51f99bab70d1aeb59675de57c78bcef18b5a2e8a5a5f.js
       I, [2018-06-23T23:22:26.277598 #917]  INFO -- : Writing /tmp/build_60a79b6db8e344f05e2fd3adead63da5/public/assets/posts-f78f0f583e152fa235ca51f99bab70d1aeb59675de57c78bcef18b5a2e8a5a5f.js.gz
       rake aborted!
       Uglifier::Error: Unterminated string constant
       /tmp/build_60a79b6db8e344f05e2fd3adead63da5/vendor/bundle/ruby/2.5.0/gems/uglifier-4.1.12/lib/uglifier.rb:234:in `parse_result'
       /tmp/build_60a79b6db8e344f05e2fd3adead63da5/vendor/bundle/ruby/2.5.0/gems/uglifier-4.1.12/lib/uglifier.rb:216:in `run_uglifyjs'
       /tmp/build_60a79b6db8e344f05e2fd3adead63da5/vendor/bundle/ruby/2.5.0/gems/uglifier-4.1.12/lib/uglifier.rb:168:in `compile'
       /tmp/build_60a79b6db8e344f05e2fd3adead63da5/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/uglifier_compressor.rb:53:in `call'
       /tmp/build_60a79b6db8e344f05e2fd3adead63da5/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/uglifier_compressor.rb:28:in `call'
       /tmp/build_60a79b6db8e344f05e2fd3adead63da5/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
       /tmp/build_60a79b6db8e344f05e2fd3adead63da5/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
       /tmp/build_60a79b6db8e344f05e2fd3adead63da5/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
       /tmp/build_60a79b6db8e344f05e2fd3adead63da5/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
       /tmp/build_60a79b6db8e344f05e2fd3adead63da5/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
       /tmp/build_60a79b6db8e344f05e2fd3adead63da5/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:60:in `block in load'
       /tmp/build_60a79b6db8e344f05e2fd3adead63da5/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
       /tmp/build_60a79b6db8e344f05e2fd3adead63da5/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:44:in `load'
       /tmp/build_60a79b6db8e344f05e2fd3adead63da5/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
       /tmp/build_60a79b6db8e344f05e2fd3adead63da5/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `load'
       /tmp/build_60a79b6db8e344f05e2fd3adead63da5/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/base.rb:66:in `find_asset'
       /tmp/build_60a79b6db8e344f05e2fd3adead63da5/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/base.rb:73:in `find_all_linked_assets'
       /tmp/build_60a79b6db8e344f05e2fd3adead63da5/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:142:in `block in find'
       /tmp/build_60a79b6db8e344f05e2fd3adead63da5/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
       /tmp/build_60a79b6db8e344f05e2fd3adead63da5/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:228:in `block in stat_tree'
       /tmp/build_60a79b6db8e344f05e2fd3adead63da5/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:212:in `block in stat_directory'
       /tmp/build_60a79b6db8e344f05e2fd3adead63da5/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:209:in `each'
       /tmp/build_60a79b6db8e344f05e2fd3adead63da5/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:209:in `stat_directory'
       /tmp/build_60a79b6db8e344f05e2fd3adead63da5/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:227:in `stat_tree'
       /tmp/build_60a79b6db8e344f05e2fd3adead63da5/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:105:in `each'
       /tmp/build_60a79b6db8e344f05e2fd3adead63da5/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:105:in `block in logical_paths'
       /tmp/build_60a79b6db8e344f05e2fd3adead63da5/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:104:in `each'
       /tmp/build_60a79b6db8e344f05e2fd3adead63da5/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:104:in `logical_paths'
       /tmp/build_60a79b6db8e344f05e2fd3adead63da5/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:140:in `find'
       /tmp/build_60a79b6db8e344f05e2fd3adead63da5/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:186:in `compile'
       /tmp/build_60a79b6db8e344f05e2fd3adead63da5/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
       /tmp/build_60a79b6db8e344f05e2fd3adead63da5/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/rake/sprocketstask.rb:147:in `with_logger'
       /tmp/build_60a79b6db8e344f05e2fd3adead63da5/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
       /tmp/build_60a79b6db8e344f05e2fd3adead63da5/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
       Tasks: TOP => assets:precompile
       (See full trace by running task with --trace)
 !
 !     Precompiling assets failed.
 !
 !     Push rejected, failed to compile Ruby app.
 !     Push failed
```

**Comment by andresfdezc** [comment]
El error importante es éste al parecer:

```
Uglifier::Error: Unterminated string constant
```

Por favor verifiquen que el código en javascript que escribieron en su aplicación no tenga errores de sintaxis. La aplicación puede haber estado funcionando con normalidad porque ese código no lo ejecutaban, pero necesita estar bueno para que se pueda subir a Heroku.
