### ISSUE TITLE
Error en deploy de heroku - yarn?

### ISSUE THREAD

**Issue by dtfuller** [IIC2143-2018-1/project#67]
Hola a todos, 

Algo no me está permitiendo hacer push. Localmente el rails build funciona perfecto. Entiendo que al hacer push a heroku, todo se compila en el servidor remote, sin embargo, solo por descartar tengo instalado Yarn (probé instalando via homebrew y npm). 

De antemano, muchas gracias 👍 

```
davidfuller at Davids-MBP-2 in ~/Dev/grupo40-iic2143 on master
$ git push heroku master
Counting objects: 176, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (168/168), done.
Writing objects: 100% (176/176), 38.59 KiB | 0 bytes/s, done.
Total 176 (delta 81), reused 25 (delta 1)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Ruby app detected
remote: -----> Compiling Ruby/Rails
remote: -----> Using Ruby version: ruby-2.3.7
remote: -----> Installing dependencies using bundler 1.15.2
remote:        Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
remote:        Warning: the running version of Bundler (1.15.2) is older than the version that created the lockfile (1.16.1). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
remote:        Fetching gem metadata from https://rubygems.org/........
remote:        Fetching version metadata from https://rubygems.org/..
remote:        Fetching dependency metadata from https://rubygems.org/.
remote:        Using rake 12.3.1
remote:        Using concurrent-ruby 1.0.5
remote:        Using minitest 5.11.3
remote:        Using thread_safe 0.3.6
remote:        Using builder 3.2.3
remote:        Using erubi 1.7.1
remote:        Using mini_portile2 2.3.0
remote:        Using crass 1.0.4
remote:        Using rack 2.0.4
remote:        Using nio4r 2.3.0
remote:        Using websocket-extensions 0.1.3
remote:        Using mini_mime 1.0.0
remote:        Using arel 8.0.0
remote:        Fetching aws_cf_signer 0.1.3
remote:        Using bcrypt 3.1.11
remote:        Using method_source 0.9.0
remote:        Using thor 0.20.0
remote:        Using bundler 1.15.2
remote:        Using cancancan 2.2.0
remote:        Fetching chartkick 2.3.5
remote:        Using climate_control 0.2.0
remote:        Fetching unf_ext 0.0.7.5
remote:        Installing aws_cf_signer 0.1.3
remote:        Using mime-types-data 3.2016.0521
remote:        Fetching netrc 0.11.0
remote:        Installing chartkick 2.3.5
remote:        Installing netrc 0.11.0
remote:        Using coffee-script-source 1.12.2
remote:        Using execjs 2.7.0
remote:        Using orm_adapter 0.5.0
remote:        Using ffi 1.9.23
remote:        Using multi_json 1.13.1
remote:        Fetching mimemagic 0.3.2
remote:        Installing unf_ext 0.0.7.5 with native extensions
remote:        Using pg 1.0.0
remote:        Using puma 3.11.4
remote:        Using rb-fsevent 0.10.3
remote:        Using tilt 2.0.8
remote:        Using turbolinks-source 5.1.0
remote:        Using i18n 0.9.5
remote:        Using tzinfo 1.2.5
remote:        Using nokogiri 1.8.2
remote:        Using rack-test 1.0.0
remote:        Using warden 1.2.7
remote:        Using sprockets 3.7.1
remote:        Using websocket-driver 0.6.5
remote:        Using mail 2.7.0
remote:        Fetching terrapin 0.6.0
remote:        Installing terrapin 0.6.0
remote:        Installing mimemagic 0.3.2
remote:        Using mime-types 3.1
remote:        Using coffee-script 2.4.1
remote:        Using uglifier 4.1.9
remote:        Using rb-inotify 0.9.10
remote:        Using turbolinks 5.1.1
remote:        Using activesupport 5.1.5
remote:        Using loofah 2.2.2
remote:        Using sass-listen 4.0.0
remote:        Using rails-dom-testing 2.0.3
remote:        Using globalid 0.4.1
remote:        Using activemodel 5.1.5
remote:        Using jbuilder 2.7.0
remote:        Using rails-html-sanitizer 1.0.4
remote:        Using sass 3.5.6
remote:        Using activejob 5.1.5
remote:        Using active_model_serializers 0.8.4
remote:        Using activerecord 5.1.5
remote:        Using actionview 5.1.5
remote:        Using actionpack 5.1.5
remote:        Using actioncable 5.1.5
remote:        Using actionmailer 5.1.5
remote:        Using railties 5.1.5
remote:        Using sprockets-rails 3.2.1
remote:        Fetching best_in_place 3.1.1
remote:        Installing best_in_place 3.1.1
remote:        Using coffee-rails 4.2.2
remote:        Using responders 2.4.0
remote:        Using font-awesome-rails 4.7.0.4
remote:        Fetching jquery-rails 4.3.3
remote:        Installing jquery-rails 4.3.3
remote:        Using rails 5.1.5
remote:        Using sass-rails 5.0.7
remote:        Fetching paperclip 6.0.0
remote:        Installing paperclip 6.0.0
remote:        Using devise 4.4.3
remote:        Using rapidfire 3.1.0
remote:        Fetching unf 0.1.4
remote:        Installing unf 0.1.4
remote:        Fetching domain_name 0.5.20180417
remote:        Installing domain_name 0.5.20180417
remote:        Fetching http-cookie 1.0.3
remote:        Installing http-cookie 1.0.3
remote:        Fetching rest-client 2.0.2
remote:        Installing rest-client 2.0.2
remote:        Fetching cloudinary 1.9.1
remote:        Installing cloudinary 1.9.1
remote:        Fetching paperclip-cloudinary 1.3.2
remote:        Installing paperclip-cloudinary 1.3.2
remote:        Bundle complete! 26 Gemfile dependencies, 83 gems now installed.
remote:        Gems in the groups development and test were not installed.
remote:        Bundled gems are installed into ./vendor/bundle.
remote:        Post-install message from paperclip:
remote:        ##################################################
remote:        #  NOTE FOR UPGRADING FROM 4.3.0 OR EARLIER      #
remote:        ##################################################
remote:
remote:        Paperclip is now compatible with aws-sdk >= 2.0.0.
remote:
remote:        If you are using S3 storage, aws-sdk >= 2.0.0 requires you to make a few small
remote:        changes:
remote:
remote:        * You must set the `s3_region`
remote:        * If you are explicitly setting permissions anywhere, such as in an initializer,
remote:          note that the format of the permissions changed from using an underscore to
remote:          using a hyphen. For example, `:public_read` needs to be changed to
remote:          `public-read`.
remote:
remote:        For a walkthrough of upgrading from 4 to 5 and aws-sdk >= 2.0 you can watch
remote:        http://rubythursday.com/episodes/ruby-snack-27-upgrade-paperclip-and-aws-sdk-in-prep-for-rails-5
remote:        Bundle completed (6.35s)
remote:        Cleaning up the bundler cache.
remote:        Warning: the running version of Bundler (1.15.2) is older than the version that created the lockfile (1.16.1). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
remote:        Removing cocaine (0.5.8)
remote:        Removing paperclip (4.3.7)
remote:        Removing mimemagic (0.3.0)
remote:        The latest bundler is 1.16.2, but you are currently running 1.15.2.
remote:        To update, run `gem install bundler`
remote: -----> Installing node-v8.10.0-linux-x64
remote: -----> Detecting rake tasks
remote: -----> Preparing app for Rails asset pipeline
**remote:        Running: rake assets:precompile
remote:        Yarn executable was not detected in the system.**
remote:        Download Yarn at https://yarnpkg.com/en/docs/install
remote:        I, [2018-06-24T21:32:44.858583 #432]  INFO -- : Writing /tmp/build_2c20751aab96f04fe8ac10d7ddea5ff8/public/assets/navigation-12fed2d631e69f5f3f3a6fe947ffa7e3c0d906cfde53c815a654599abadd30fe.css
remote:        I, [2018-06-24T21:32:44.859160 #432]  INFO -- : Writing /tmp/build_2c20751aab96f04fe8ac10d7ddea5ff8/public/assets/navigation-12fed2d631e69f5f3f3a6fe947ffa7e3c0d906cfde53c815a654599abadd30fe.css.gz
remote:        I, [2018-06-24T21:32:46.953095 #432]  INFO -- : Writing /tmp/build_2c20751aab96f04fe8ac10d7ddea5ff8/public/assets/jquery-3.2.1.min-f08d16747fb6d2e6f396fcce5bd3d771721febc5350d60dda02055d7664c1146.js
remote:        I, [2018-06-24T21:32:46.953291 #432]  INFO -- : Writing /tmp/build_2c20751aab96f04fe8ac10d7ddea5ff8/public/assets/jquery-3.2.1.min-f08d16747fb6d2e6f396fcce5bd3d771721febc5350d60dda02055d7664c1146.js.gz
remote:        I, [2018-06-24T21:32:48.343259 #432]  INFO -- : Writing /tmp/build_2c20751aab96f04fe8ac10d7ddea5ff8/public/assets/bootstrap.min-77cce082cfd274b236b5f0787442704609e19217999ea4e087abdfe88ffd001b.js
remote:        I, [2018-06-24T21:32:48.343456 #432]  INFO -- : Writing /tmp/build_2c20751aab96f04fe8ac10d7ddea5ff8/public/assets/bootstrap.min-77cce082cfd274b236b5f0787442704609e19217999ea4e087abdfe88ffd001b.js.gz
remote:        I, [2018-06-24T21:32:51.911011 #432]  INFO -- : Writing /tmp/build_2c20751aab96f04fe8ac10d7ddea5ff8/public/assets/mdb.min-25c58bff67ac83271ee54a8af97b32ec09e232906244da1ae20cf921b17e2921.js
remote:        I, [2018-06-24T21:32:51.911210 #432]  INFO -- : Writing /tmp/build_2c20751aab96f04fe8ac10d7ddea5ff8/public/assets/mdb.min-25c58bff67ac83271ee54a8af97b32ec09e232906244da1ae20cf921b17e2921.js.gz
remote:        I, [2018-06-24T21:32:52.695278 #432]  INFO -- : Writing /tmp/build_2c20751aab96f04fe8ac10d7ddea5ff8/public/assets/popper.min-b67ed2791a81e7a51fe5866f6b56b0d57d89dc72cc3038dfb8d9462396d6aec0.js
remote:        I, [2018-06-24T21:32:52.695473 #432]  INFO -- : Writing /tmp/build_2c20751aab96f04fe8ac10d7ddea5ff8/public/assets/popper.min-b67ed2791a81e7a51fe5866f6b56b0d57d89dc72cc3038dfb8d9462396d6aec0.js.gz
remote:        I, [2018-06-24T21:32:54.150071 #432]  INFO -- : Writing /tmp/build_2c20751aab96f04fe8ac10d7ddea5ff8/public/assets/select2.min-c93aa7008c1c3ff47bedf85891a89591ac758c70e2952b0c5f978dbde07950cf.js
remote:        I, [2018-06-24T21:32:54.150271 #432]  INFO -- : Writing /tmp/build_2c20751aab96f04fe8ac10d7ddea5ff8/public/assets/select2.min-c93aa7008c1c3ff47bedf85891a89591ac758c70e2952b0c5f978dbde07950cf.js.gz
remote:        rake aborted!
remote:        Uglifier::Error: Unexpected token: punc (.)
remote:        /tmp/build_2c20751aab96f04fe8ac10d7ddea5ff8/vendor/bundle/ruby/2.3.0/gems/uglifier-4.1.9/lib/uglifier.rb:234:in `parse_result'
remote:        /tmp/build_2c20751aab96f04fe8ac10d7ddea5ff8/vendor/bundle/ruby/2.3.0/gems/uglifier-4.1.9/lib/uglifier.rb:216:in `run_uglifyjs'
remote:        /tmp/build_2c20751aab96f04fe8ac10d7ddea5ff8/vendor/bundle/ruby/2.3.0/gems/uglifier-4.1.9/lib/uglifier.rb:168:in `compile'
remote:        /tmp/build_2c20751aab96f04fe8ac10d7ddea5ff8/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/compressing.rb:65:in `block in js_compressor='
remote:        /tmp/build_2c20751aab96f04fe8ac10d7ddea5ff8/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/legacy_proc_processor.rb:31:in `call'
remote:        /tmp/build_2c20751aab96f04fe8ac10d7ddea5ff8/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
remote:        /tmp/build_2c20751aab96f04fe8ac10d7ddea5ff8/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
remote:        /tmp/build_2c20751aab96f04fe8ac10d7ddea5ff8/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
remote:        /tmp/build_2c20751aab96f04fe8ac10d7ddea5ff8/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
remote:        /tmp/build_2c20751aab96f04fe8ac10d7ddea5ff8/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
remote:        /tmp/build_2c20751aab96f04fe8ac10d7ddea5ff8/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
remote:        /tmp/build_2c20751aab96f04fe8ac10d7ddea5ff8/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
remote:        /tmp/build_2c20751aab96f04fe8ac10d7ddea5ff8/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
remote:        /tmp/build_2c20751aab96f04fe8ac10d7ddea5ff8/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
remote:        /tmp/build_2c20751aab96f04fe8ac10d7ddea5ff8/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
remote:        /tmp/build_2c20751aab96f04fe8ac10d7ddea5ff8/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:66:in `find_asset'
remote:        /tmp/build_2c20751aab96f04fe8ac10d7ddea5ff8/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:73:in `find_all_linked_assets'
remote:        /tmp/build_2c20751aab96f04fe8ac10d7ddea5ff8/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:142:in `block in find'
remote:        /tmp/build_2c20751aab96f04fe8ac10d7ddea5ff8/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
remote:        /tmp/build_2c20751aab96f04fe8ac10d7ddea5ff8/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:228:in `block in stat_tree'
remote:        /tmp/build_2c20751aab96f04fe8ac10d7ddea5ff8/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:212:in `block in stat_directory'
remote:        /tmp/build_2c20751aab96f04fe8ac10d7ddea5ff8/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:209:in `each'
remote:        /tmp/build_2c20751aab96f04fe8ac10d7ddea5ff8/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:209:in `stat_directory'
remote:        /tmp/build_2c20751aab96f04fe8ac10d7ddea5ff8/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:227:in `stat_tree'
remote:        /tmp/build_2c20751aab96f04fe8ac10d7ddea5ff8/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:105:in `each'
remote:        /tmp/build_2c20751aab96f04fe8ac10d7ddea5ff8/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:105:in `block in logical_paths'
remote:        /tmp/build_2c20751aab96f04fe8ac10d7ddea5ff8/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:104:in `each'
remote:        /tmp/build_2c20751aab96f04fe8ac10d7ddea5ff8/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:104:in `logical_paths'
remote:        /tmp/build_2c20751aab96f04fe8ac10d7ddea5ff8/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:140:in `find'
remote:        /tmp/build_2c20751aab96f04fe8ac10d7ddea5ff8/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:185:in `compile'
remote:        /tmp/build_2c20751aab96f04fe8ac10d7ddea5ff8/vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
remote:        /tmp/build_2c20751aab96f04fe8ac10d7ddea5ff8/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/rake/sprocketstask.rb:147:in `with_logger'
remote:        /tmp/build_2c20751aab96f04fe8ac10d7ddea5ff8/vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
remote:        /tmp/build_2c20751aab96f04fe8ac10d7ddea5ff8/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
remote:        Tasks: TOP => assets:precompile
remote:        (See full trace by running task with --trace)
remote:  !
remote:  !     Precompiling assets failed.
remote:  !
remote:  !     Push rejected, failed to compile Ruby app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !	Push rejected to grupo40-iic2143.
remote:
To https://git.heroku.com/grupo40-iic2143.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/grupo40-iic2143.git'
```

**Comment by andresfdezc** [comment]
El error importante parece ser este:

`Uglifier::Error: Unexpected token: punc (.)`

Porfa mira la issue #66.
